# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e707df602273a9af8480d16e4ad40c59"
application_url = "https://flow-extensions--development.gadget.app/api/shopify/install-or-render"
embedded = true
name = "Flow Extensions"
handle = "flow-extensions"

[webhooks]
api_version = "2025-01"

[auth]
redirect_urls = [
  "https://flow-extensions--development.gadget.app/api/connections/auth/shopify/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "kalen-test-store.myshopify.com"
include_config_on_deploy = true
